# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: splash
universal_binaries:
  - name_template: splash
    replace: false
before:
  hooks:
    - go mod tidy
builds:
  - binary: splash
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X "main.ClientId={{ .Env.UNSPLASH_CLIENT_ID }}"
      - -s -w -X "main.ClientSecret={{ .Env.UNSPLASH_CLIENT_SECRET }}"
      - -s -w -X "main.Debug={{ .Env.DEBUG }}"
      - -s -w -X "github.com/rawnly/splash-cli/config.Version={{ .Version }}"
      - -s -w -X "github.com/rawnly/splash-cli/config.Commit={{ .Commit }}"
    goos:
      - linux
      - windows
      - darwin
brews:
  - name: splash-cli
    homepage: https://splash-cli.app
    license: MIT
    folder: Formula
    description: Splash is a command line interface for Unsplash.
    tap:
      owner: rawnly
      name: homebrew-tap
      branch: master
    commit_author:
      name: Goreleaser BOT
      email: goreleaser@fedevitale.dev
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
release:
  prerelease: auto
  github:
    owner: rawnly
    name: splash-cli
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-alpha"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
